version: '3.7'
services:
  web:
    build: nginx
    image: "tishenko/hw01-web:0.2"
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - backend
  app:
    build: app
    image: "tishenko/hw01-app:0.2"
    networks:
      - backend

networks:
  backend:

